services:
  - type: web
    name: xd-chat-app
    env: docker
    repo: https://github.com/realvoidgojo/XD-Chat-app
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health.php
    envVars:
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_USERNAME
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
      - key: SUPABASE_DATABASE
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    disk:
      name: uploads
      mountPath: /var/www/html/uploads
      sizeGB: 1
